### PR TITLE
Respect min and max attributes

### PR DESCRIPTION
**Pull request by csaggo**
I think it would be nice to respect the min and max attribute if they are set.

### CODE REVIEW

**Comment by joshua-s** [comment]
@csaggo excellent idea! Thank you for this.

**Comment by joshua-s** [comment]
@csaggo I am having an issue.

My markup:
```html
<input type="number" min="4" max="10">
```

The + button does not seem to increment the value after a couple clicks. I also face this bug when an initial value is set that is in within the valid range:

```html
<input type="number" min="4" max="10" value="5">
```
I did some examination and `attrMax > currentInput.value` is returning false even though it should return true.

Do you have any ideas? I didn't put much time into hunting down the error, but can do so if you would like.

**Comment by csaggo** [comment]
@joshua-s 
Hi Joshua. It works fine for me. Did you by any chance manipulate the field through devtools or did you really render it with the attributes from the go?
If you add the attribute later with devtools, it does not work for me either.

**Comment by csaggo** [comment]
PS: tested in FF, Safari and Chrome. all good.

**Comment by csaggo** [comment]
meh got it. those things are strings ... with parseFloat it works :)

**Comment by joshua-s** [comment]
@csaggo looks good, thanks for the code and the fix!

**Pull request merged**
